// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-IyhFeUHVPxYvP8psjfYLWKNpRTegApU',
    appId: '1:529373949117:web:fd3fb3f1e8eac4fc711bd4',
    messagingSenderId: '529373949117',
    projectId: 'propertymanagerapp-c4961',
    authDomain: 'propertymanagerapp-c4961.firebaseapp.com',
    storageBucket: 'propertymanagerapp-c4961.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHwjYkYmNtIuTiqfk5UuNK9znAdERXS7A',
    appId: '1:529373949117:android:b83fa33c99f4224e711bd4',
    messagingSenderId: '529373949117',
    projectId: 'propertymanagerapp-c4961',
    storageBucket: 'propertymanagerapp-c4961.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuSFgrraHSPDNcFidxlYTLSYq17KrfhDQ',
    appId: '1:529373949117:ios:a8a75cb33e540243711bd4',
    messagingSenderId: '529373949117',
    projectId: 'propertymanagerapp-c4961',
    storageBucket: 'propertymanagerapp-c4961.firebasestorage.app',
    iosBundleId: 'com.example.propertyManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuSFgrraHSPDNcFidxlYTLSYq17KrfhDQ',
    appId: '1:529373949117:ios:a8a75cb33e540243711bd4',
    messagingSenderId: '529373949117',
    projectId: 'propertymanagerapp-c4961',
    storageBucket: 'propertymanagerapp-c4961.firebasestorage.app',
    iosBundleId: 'com.example.propertyManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-IyhFeUHVPxYvP8psjfYLWKNpRTegApU',
    appId: '1:529373949117:web:b6caf86cc144b929711bd4',
    messagingSenderId: '529373949117',
    projectId: 'propertymanagerapp-c4961',
    authDomain: 'propertymanagerapp-c4961.firebaseapp.com',
    storageBucket: 'propertymanagerapp-c4961.firebasestorage.app',
  );

}